# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: temperature_service.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'temperature_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19temperature_service.proto\x12\x0btemperature\x1a\x1bgoogle/protobuf/empty.proto\"\x97\x01\n\x11TemperatureRecord\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x11\n\tsensor_id\x18\x02 \x01(\t\x12\x18\n\x10source_timestamp\x18\x03 \x01(\t\x12\x14\n\x0cprocessed_at\x18\x04 \x01(\t\x12\x13\n\x0btemperature\x18\x05 \x01(\x01\x12\x1e\n\x16moving_average_last_2h\x18\x06 \x01(\x01\"O\n\x0eLatestResponse\x12\r\n\x05\x66ound\x18\x01 \x01(\x08\x12.\n\x06record\x18\x02 \x01(\x0b\x32\x1e.temperature.TemperatureRecord\"\x1f\n\x0eHistoryRequest\x12\r\n\x05limit\x18\x01 \x01(\x05\"B\n\x0fHistoryResponse\x12/\n\x07records\x18\x01 \x03(\x0b\x32\x1e.temperature.TemperatureRecord2\x9f\x01\n\x12TemperatureService\x12@\n\tGetLatest\x12\x16.google.protobuf.Empty\x1a\x1b.temperature.LatestResponse\x12G\n\nGetHistory\x12\x1b.temperature.HistoryRequest\x1a\x1c.temperature.HistoryResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'temperature_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TEMPERATURERECORD']._serialized_start=72
  _globals['_TEMPERATURERECORD']._serialized_end=223
  _globals['_LATESTRESPONSE']._serialized_start=225
  _globals['_LATESTRESPONSE']._serialized_end=304
  _globals['_HISTORYREQUEST']._serialized_start=306
  _globals['_HISTORYREQUEST']._serialized_end=337
  _globals['_HISTORYRESPONSE']._serialized_start=339
  _globals['_HISTORYRESPONSE']._serialized_end=405
  _globals['_TEMPERATURESERVICE']._serialized_start=408
  _globals['_TEMPERATURESERVICE']._serialized_end=567
# @@protoc_insertion_point(module_scope)
